#pragma once
#ifndef ERR_LCD_HPP__
#define ERR_LCD_HPP__

#define LCD_ERR_FAILED_READ_CONFIG_AP_SSID "001"
#define LCD_ERR_FAILED_READ_CONFIG_AP_PASS "002"
#define LCD_ERR_FAILED_READ_CONFIG_STA_SSID "003"
#define LCD_ERR_FAILED_READ_CONFIG_STA_PASS "004"

#endif

